"use client";
import { createContext, useContext, useState } from "react";

const translations = {
  en: {
    heroTitle: "Dr. Shubham Singhal",
    heroSubtitle: "Clinical Psychologist | Special Educator",
    heroDesc: "Helping you understand your mind through therapy, analogies, and cognitive clarity.",
    bookSession: "Book a Session",
    readBlog: "Read the Blog",
    navAbout: "About",
    navServices: "Services",
    navReviews: "Reviews",
    navContact: "Contact",
    mythTitle: "Breaking the Stigma",
    mythSubtitle: "Let's separate fact from fiction when it comes to therapy and mental health in India.",
    mythHover: "Hover to reveal reality",
    mythHowItWorks: "How it works?",
    mythJourney: "The Journey of Transformation",
    approachTitle: "My Approach",
    approachSubtitle: "Every individual carries a story. My goal is to listen deeply, understand with clarity, and walk alongside you as we navigate the healing journey.",
    approachHeading: "your healing is our responsibility",
    exploreServices: "Explore Our Services",
    servicesTitle: "Helping you heal, grow, and thrive — one session at a time.",
    helpTitle: "Whatever you are feeling right now.",
    testTitle: "Words That Matter",
    testSubtitle: "Real voices from those who found clarity, calm, and connection.",
    aboutTitle: "Meet Dr. Shubham Singhal",
    aboutP1: "Feeling stressed, anxious, overwhelmed, or emotionally exhausted? Professional psychological support is available in a safe, private, and non-judgmental environment for children, adolescents, and adults.",
    aboutP2: "With over 6 years of clinical experience, Dr. Shubham Singhal provides support for anxiety, depression, panic, OCD, overthinking, sleep difficulties, relationship concerns, and academic stress. As a Clinical Psychologist and Special Educator, he also offers assessment and intervention for Autism, ADHD, learning disabilities, visual impairment, and behavioral concerns.",
    aboutP3: "He is an award-winning psychologist with international certifications in depression, anxiety, and autism from Harvard University, Birmingham University, Glasgow University, York University, and King's College London.",
    quote: "“Healing happens where stories are heard with empathy and held with care.”",
    approachPoint1: "Client-centered and empathetic sessions",
    approachPoint2: "Evidence-based therapeutic methods",
    approachPoint3: "Focus on long-term emotional resilience",
    approachPoint4: "Safe, non-judgmental space for self-exploration",
    featTrusted: "trusted",
    featTrustedDesc: "therapist at your service",
    featSafe: "safe",
    featSafeDesc: "space for you",
    featAffordable: "affordable",
    featAffordableDesc: "pricing plans",
    featFlexible: "flexible",
    featFlexibleDesc: "chat, call, video sessions",
    srvInd: "Individual Therapy",
    srvIndDesc: "Personal one-on-one sessions to help you understand and manage your emotions.",
    srvCouple: "Couples Therapy",
    srvCoupleDesc: "Work through relationship challenges with guidance and support.",
    srvTeen: "Child Therapy",
    srvTeenDesc: "Safe space for adolescents to express and explore their feelings.",
    srvPsych: "Psychiatric Therapy",
    srvPsychDesc: "Professional medical guidance for mental health through diagnosis and treatment.",
    journeyTitle: "The Journey of Transformation",
    journeySubtitle: "\"Even the darkest night will end and the sun will rise.\"",
    journeyTangled: "The Tangled Mind",
    journeyStep1Title: "Step 1: Reaching Out & Acknowledgment",
    journeyStep1P1: "When we are overwhelmed by anxiety or depression, our mind feels like an untamable knot. Winston Churchill famously referred to his severe depression as his \"black dog.\" He didn't hide from it; he acknowledged it.",
    journeyStep1P2: "The first step in therapy is simply acknowledging that the knot exists. You don't need to know how to untie it yet. In our first session, we just sit together and look at the \"black dog\" without fear, without judgment. We begin the slow, gentle process of unravelling the threads.",
    journeyLight: "Finding the Light",
    journeyStep2Title: "Step 2: Exploring the Roots & Building Tools",
    journeyStep2P1: "Abraham Lincoln suffered from such profound \"melancholy\" (depression) that his friends feared for his life. Yet, it was this exact suffering that gave him the deep empathy required to heal a fractured, warring nation.",
    journeyStep2P2: "In therapy, we don't just banish the darkness. We explore it to find the cracks where the light gets in. We understand your triggers, your past, and your patterns. Then, we build evidence-based psychological tools so you can harness your own emotional depth as a strength, just like Lincoln did.",
    journeyKintsugi: "The Art of Brokenness",
    journeyStep3Title: "Step 3: Healing, Growth, and Kintsugi",
    journeyStep3P1: "In Japan, when a ceramic bowl breaks, they don't throw it away. They repair the cracks with lacquer mixed with powdered gold. This art is called Kintsugi.",
    journeyStep3P2: "The philosophy is profound: the breakage and repair are part of the object's history, not something to disguise. In our final stages of therapy, you aren't \"fixed\" to return to who you were before. You are healed, and your scars—your struggles, your survival—are lined with gold. You become more resilient, more beautiful, and more uniquely you.",
    journeyCTA: "Your Story Is Waiting to Be Written",
    journeyCTADesc: "You don't have to navigate the darkness alone. Whether your mind feels tangled or you're looking for the gold to repair the cracks, we are here to walk the journey with you.",
    journeyButton: "Take the First Step on WhatsApp",
    "child behavioral problems": "child behavioral problems",
    "Sleep problems": "sleep problems",
    "Stress and Anger Management": "stress and anger management",
    "Fear and Panic Related Issues": "fear and panic related issues",
    "Grief and Trauma": "grief and trauma",
    "eating disorders": "eating disorders",
    "body image issues": "body image issues",
    "relationship issues": "relationship issues",
    "depression": "depression",
    "anger management": "anger management",
    "irrational fear": "irrational fear",
    "cognitive distortion": "cognitive distortion",
    "gaslighting": "gaslighting",
    "procrastination": "procrastination",
    "intrusive thoughts": "intrusive thoughts",
    "narcissism": "narcissism",
    "social anxiety": "social anxiety",
    "ocd": "ocd",
    "addiction": "addiction",
    "burnout": "burnout",
    "anxiety": "anxiety",
    "stress": "stress",
    "trauma": "trauma",
    footSubtitle: "Clinical Psychologist | Special Educator",
    footDesc: "Helping you navigate through thought, emotion, and identity.",
    footExplore: "Explore",
    footResources: "Resources",
    footBlog: "Blog",
    footPrivacy: "Privacy Policy",
    footConnect: "Connect",
    footEmail: "Email: shubhamsinghal@gmail.com",
    footMobile: "Mobile: +91 8076 449 095",
    footLocation: "Location: SRG hospital, Block E2, Shastri Nagar, New Delhi, Delhi, 110052",
    footRights: "Dr. Shubham Singhal. All rights reserved.",
    trainedTitle: "Trained From",
    ladderTitle: "Quick Help",
    ladderQ1: "Who are you seeking help for?",
    ladderQ2: "What is the main challenge?",
    ladderQ3: "How long has this been going on?",
    optMyself: "Myself",
    optChild: "My Child",
    optPartner: "My Partner",
    optOther: "Someone Else",
    optStress: "Stress or Anxiety",
    optSad: "Feeling Sad/Low",
    optRelation: "Relationship Issues",
    optOverthink: "Overthinking/Panic",
    optDays: "Just started (Days)",
    optWeeks: "A few weeks",
    optMonths: "A few months",
    optYears: "A long time (Years)",
    ladderBack: "Back",
    waIntro: "Hi Dr. Shubham, I am reaching out for",
    waBecause: "because the main issue is",
    waAnd: "and this has been going on for",
  },
  hi: {
    heroTitle: "डॉ. शुभम सिंघल",
    heroSubtitle: "क्लीनिकल साइकोलॉजिस्ट | स्पेशल एजुकेटर",
    heroDesc: "थेरेपी और आसान उदाहरणों के जरिए आपको अपने मन को समझने में मदद करना।",
    bookSession: "सेशन बुक करें",
    readBlog: "ब्लॉग पढ़ें",
    navAbout: "मेरे बारे में",
    navServices: "सेवाएं",
    navReviews: "रिव्यु",
    navContact: "संपर्क करें",
    mythTitle: "गलतफहमियां दूर करें",
    mythSubtitle: "आइए भारत में थेरेपी और मेंटल हेल्थ को लेकर सच और झूठ के बीच का फर्क समझें।",
    mythHover: "सच देखने के लिए होवर करें",
    mythHowItWorks: "यह कैसे काम करता है?",
    mythJourney: "बदलाव का सफर",
    approachTitle: "मेरा तरीका",
    approachSubtitle: "हर इंसान की अपनी एक कहानी होती है। मेरा लक्ष्य है आपकी बात को गहराई से सुनना, उसे सही से समझना और आपके इस सफर में आपका साथ देना।",
    approachHeading: "आपका बेहतर होना हमारी ज़िम्मेदारी है",
    exploreServices: "हमारी सेवाएं देखें",
    servicesTitle: "एक बार में एक सेशन - आपको बेहतर महसूस करने और आगे बढ़ने में मदद करना।",
    helpTitle: "आप जो भी महसूस कर रहे हैं, हम समझ सकते हैं।",
    testTitle: "सच्चे अनुभव",
    testSubtitle: "उन लोगों की आवाज़ें जिन्हें शांति और सही रास्ता मिला।",
    aboutTitle: "डॉ. शुभम सिंघल से मिलें",
    aboutP1: "तनाव, चिंता, घबराहट या बहुत ज्यादा थका हुआ महसूस कर रहे हैं? बच्चों, युवाओं और बड़ों के लिए एक सुरक्षित और प्राइवेट माहौल में प्रोफेशनल मदद उपलब्ध है, जहां आपको कोई जज नहीं करेगा।",
    aboutP2: "6 साल से ज्यादा के क्लीनिकल अनुभव के साथ, डॉ. शुभम सिंघल चिंता, उदासी (डिप्रेशन), घबराहट (पैनिक), OCD, बहुत ज्यादा सोचना (ओवरथिंकिंग), नींद की परेशानी, रिश्तों की उलझन और पढ़ाई के तनाव में मदद करते हैं। एक क्लीनिकल साइकोलॉजिस्ट और स्पेशल एजुकेटर के रूप में, वे ऑटिज़्म, ADHD, सीखने में दिक्कत, और बिहेवियर (व्यवहार) से जुड़ी परेशानियों के लिए भी मदद देते हैं।",
    aboutP3: "वे एक अवार्ड जीतने वाले साइकोलॉजिस्ट हैं, जिनके पास हार्वर्ड यूनिवर्सिटी, बर्मिंघम यूनिवर्सिटी, ग्लासगो यूनिवर्सिटी, यॉर्क यूनिवर्सिटी और किंग्स कॉलेज लंदन से डिप्रेशन, एंग्जायटी और ऑटिज़्म में इंटरनेशनल सर्टिफिकेट हैं।",
    quote: "“हीलिंग (सुधार) वहीं से शुरू होती है, जहां आपकी कहानी को पूरे ध्यान और परवाह के साथ सुना जाता है।”",
    approachPoint1: "आप पर फोकस और समझने वाले सेशन",
    approachPoint2: "रिसर्च पर आधारित असरदार तरीके",
    approachPoint3: "लंबे समय तक आपको मजबूत बनाने पर फोकस",
    approachPoint4: "खुद को समझने के लिए एक सुरक्षित जगह, जहां कोई जजमेंट नहीं",
    featTrusted: "भरोसेमंद",
    featTrustedDesc: "आपकी मदद के लिए थेरेपिस्ट",
    featSafe: "सुरक्षित",
    featSafeDesc: "आपके लिए एक सेफ जगह",
    featAffordable: "बजट में",
    featAffordableDesc: "सही कीमत वाले प्लान",
    featFlexible: "सुविधा के अनुसार",
    featFlexibleDesc: "चैट, कॉल, या वीडियो सेशन",
    srvInd: "पर्सनल थेरेपी (अकेले)",
    srvIndDesc: "अपनी भावनाओं को समझने और उन्हें हैंडल करने के लिए आमने-सामने के सेशन।",
    srvCouple: "कपल थेरेपी (जोड़ों के लिए)",
    srvCoupleDesc: "सही गाइडेंस और सपोर्ट के साथ अपने रिश्ते की मुश्किलों को सुलझाएं।",
    srvTeen: "टीन थेरेपी (युवाओं के लिए)",
    srvTeenDesc: "युवाओं को अपनी भावनाएं बताने और खुद को समझने के लिए एक सेफ जगह।",
    srvPsych: "मनोरोग चिकित्सा (साइकेट्रिक)",
    srvPsychDesc: "सही जांच और इलाज के जरिए मेंटल हेल्थ के लिए प्रोफेशनल मेडिकल सलाह।",
    journeyTitle: "बदलाव का सफर",
    journeySubtitle: "\"चाहे रात कितनी भी अंधेरी हो, सवेरा जरूर होता है।\"",
    journeyTangled: "उलझा हुआ मन",
    journeyStep1Title: "कदम 1: मदद मांगना और मानना",
    journeyStep1P1: "जब हम एंग्जायटी या डिप्रेशन में होते हैं, तो हमारा दिमाग एक बहुत उलझी हुई गांठ जैसा लगता है। विंस्टन चर्चिल ने अपने गहरे डिप्रेशन को अपना \"काला कुत्ता\" कहा था। वे इससे छिपे नहीं, बल्कि इसे मान लिया।",
    journeyStep1P2: "थेरेपी में पहला कदम सिर्फ यह मानना है कि हां, यह उलझन है। आपको अभी यह जानने की जरूरत नहीं है कि इसे कैसे सुलझाना है। हमारे पहले सेशन में, हम बस एक साथ बैठते हैं और बिना डरे, बिना जज किए इस \"काले कुत्ते\" को देखते हैं। हम धीरे-धीरे और आराम से इस गांठ को खोलना शुरू करते हैं।",
    journeyLight: "रौशनी ढूंढना",
    journeyStep2Title: "कदम 2: जड़ों को खोजना और तरीके बनाना",
    journeyStep2P1: "अब्राहम लिंकन को इतना गहरा डिप्रेशन था कि उनके दोस्तों को उनकी जान की फिक्र रहती थी। फिर भी, इसी दर्द ने उन्हें दूसरों का दुख समझने की वह ताकत दी, जिससे उन्होंने एक टूटे हुए देश को जोड़ दिया।",
    journeyStep2P2: "थेरेपी में, हम सिर्फ अंधेरे को दूर नहीं भगाते। हम उसमें जाते हैं ताकि देख सकें कि रौशनी कहां से आ सकती है। हम आपकी ट्रिगर्स, आपके अतीत और आपके सोचने के तरीकों को समझते हैं। फिर, हम कुछ ऐसे साइकोलॉजिकल टूल्स (तरीके) बनाते हैं ताकि आप अपनी इस गहराई को अपनी ताकत बना सकें, ठीक लिंकन की तरह।",
    journeyKintsugi: "टूटेपन को खूबसूरत बनाना (किंत्सुगी)",
    journeyStep3Title: "कदम 3: सुधार, विकास, और किंत्सुगी",
    journeyStep3P1: "जापान में, जब कोई सिरेमिक का बर्तन टूट जाता है, तो उसे फेंका नहीं जाता। वे दरारों को सोने के पाउडर से भरकर जोड़ते हैं। इस कला को 'किंत्सुगी' कहते हैं।",
    journeyStep3P2: "इसका मतलब बहुत गहरा है: टूटना और फिर से जुड़ना उस बर्तन के इतिहास का हिस्सा है, कोई ऐसी चीज़ नहीं जिसे छिपाया जाए। थेरेपी के आखिरी हिस्सों में, आप बिल्कुल पहले जैसे इंसान बनने के लिए \"फिक्स\" (ठीक) नहीं होते। बल्कि आप हील (बेहतर) हो जाते हैं, और आपके संघर्षों के निशान सोने से सजे होते हैं। आप पहले से ज्यादा मजबूत, ज्यादा खूबसूरत और अपने आप में बहुत खास बन जाते हैं।",
    journeyCTA: "आपकी कहानी लिखी जानी बाकी है",
    journeyCTADesc: "आपको इस अंधेरे में अकेले चलने की जरूरत नहीं है। चाहे आपका दिमाग उलझा हुआ लगे या आप उन दरारों को सोने से जोड़ने की कोशिश कर रहे हों, हम इस सफर में आपके साथ चलने के लिए यहां हैं।",
    journeyButton: "व्हाट्सएप पर अपना पहला कदम उठाएं",
    "child behavioral problems": "बच्चों के व्यवहार की समस्याएं",
    "Sleep problems": "नींद की परेशानी",
    "Stress and Anger Management": "तनाव और गुस्सा नियंत्रण",
    "Fear and Panic Related Issues": "डर और घबराहट",
    "Grief and Trauma": "दुख और गहरा सदमा",
    "eating disorders": "खाने से जुड़ी परेशानियां",
    "body image issues": "बॉडी इमेज (शरीर) की चिंता",
    "relationship issues": "रिश्तों की दिक्कतें",
    "depression": "उदासी (डिप्रेशन)",
    "anger management": "गुस्सा आना",
    "irrational fear": "बिना वजह का डर",
    "cognitive distortion": "नेगेटिव सोच",
    "gaslighting": "गैसलाइटिंग",
    "procrastination": "काम टालना",
    "intrusive thoughts": "बार-बार अजीब ख्याल आना",
    "narcissism": "खुद को ही सब कुछ समझना",
    "social anxiety": "लोगों से मिलने में घबराहट",
    "ocd": "OCD (बार-बार एक ही काम करना)",
    "addiction": "लत लगना",
    "burnout": "बहुत ज्यादा थकावट",
    "anxiety": "बेचैनी (एंग्जायटी)",
    "stress": "तनाव (स्ट्रेस)",
    "trauma": "गहरा सदमा (ट्रॉमा)",
    footSubtitle: "क्लीनिकल साइकोलॉजिस्ट | स्पेशल एजुकेटर",
    footDesc: "विचारों, भावनाओं और पहचान की उलझनों को सुलझाने में आपकी मदद करना।",
    footExplore: "लिंक्स",
    footResources: "जानकारी",
    footBlog: "ब्लॉग",
    footPrivacy: "प्राइवेसी पॉलिसी",
    footConnect: "हमसे जुड़ें",
    footEmail: "ईमेल: shubhamsinghal@gmail.com",
    footMobile: "फ़ोन: +91 8076 449 095",
    footLocation: "पता: एसआरजी अस्पताल, ब्लॉक ई2, शास्त्री नगर, नई दिल्ली, दिल्ली, 110052",
    footRights: "डॉ. शुभम सिंघल। सर्वाधिकार सुरक्षित।",
    trainedTitle: "हमारी पढ़ाई व ट्रेनिंग",
    ladderTitle: "मदद पाएं",
    ladderQ1: "आप किसके लिए मदद चाह रहे हैं?",
    ladderQ2: "मुख्य परेशानी क्या है?",
    ladderQ3: "यह कब से हो रहा है?",
    optMyself: "खुद के लिए",
    optChild: "मेरे बच्चे के लिए",
    optPartner: "मेरे पार्टनर के लिए",
    optOther: "किसी और के लिए",
    optStress: "तनाव या बेचैनी",
    optSad: "उदासी या निराशा",
    optRelation: "रिश्तों में दिक्कतें",
    optOverthink: "ज़्यादा सोचना / घबराहट",
    optDays: "अभी शुरू हुआ है (कुछ दिन)",
    optWeeks: "कुछ हफ्तों से",
    optMonths: "कुछ महीनों से",
    optYears: "लंबे समय से (सालों से)",
    ladderBack: "पीछे जाएं",
    waIntro: "नमस्ते डॉ. शुभम, मैं",
    waBecause: "के लिए संपर्क कर रहा/रही हूँ क्योंकि मुख्य समस्या",
    waAnd: "है, और यह",
  },
  hinglish: {
    heroTitle: "Dr. Shubham Singhal",
    heroSubtitle: "Clinical Psychologist | Special Educator",
    heroDesc: "Feeling stuck? Let's decode your mind and vibe check your thoughts together.",
    bookSession: "Book a Sesh",
    readBlog: "Read the Tea",
    navAbout: "Who Am I",
    navServices: "What I Do",
    navReviews: "Vibe Check",
    navContact: "Slide in DMs",
    mythTitle: "Busting the Myths 🧢",
    mythSubtitle: "No cap, let's clear up the fake news about therapy in India.",
    mythHover: "Hover to drop truth bombs",
    mythHowItWorks: "How does this even work?",
    mythJourney: "The Glow Up Journey",
    approachTitle: "My Vibe & Approach",
    approachSubtitle: "Everyone has a story. I’m here to listen, get where you're coming from, and help you level up mentally.",
    approachHeading: "your healing, our responsibility",
    exploreServices: "Check Out What I Do",
    servicesTitle: "Leveling up your mental health — one sesh at a time.",
    helpTitle: "Whatever vibe you're feeling right now.",
    testTitle: "The Word on the Street",
    testSubtitle: "Real talk from people who found their peace and clarity.",
    aboutTitle: "Meet Dr. Shubham Singhal",
    aboutP1: "Feeling stressed, anxious, or just totally overwhelmed? You can get legit professional help in a safe, private, and no-judgment zone for kids, teens, and adults.",
    aboutP2: "With 6+ years of clinical experience, Dr. Shubham Singhal helps out with anxiety, depression, panic, OCD, overthinking, sleep issues, relationship drama, and academic stress. As a Clinical Psychologist and Special Educator, he also does assessments and interventions for Autism, ADHD, learning disabilities, visual impairment, and behavioral stuff.",
    aboutP3: "He's an award-winning psychologist flexing international certifications in depression, anxiety, and autism from Harvard University, Birmingham University, Glasgow University, York University, and King's College London.",
    quote: "“Healing is a total vibe when you actually feel heard and understood.”",
    approachPoint1: "You-first, no-judgment sessions",
    approachPoint2: "Science-backed healing methods",
    approachPoint3: "Building strong mental resilience",
    approachPoint4: "Safe space to let it all out",
    featTrusted: "trusted",
    featTrustedDesc: "therapist on standby",
    featSafe: "safe",
    featSafeDesc: "vibe zone",
    featAffordable: "budget-friendly",
    featAffordableDesc: "plans for you",
    featFlexible: "flexible",
    featFlexibleDesc: "chat, voice, or video",
    srvInd: "1-on-1 Therapy",
    srvIndDesc: "Personal sessions to decode your feelings and get your mind right.",
    srvCouple: "Couples Therapy",
    srvCoupleDesc: "Fix the red flags and build a healthier dynamic together.",
    srvTeen: "Child Therapy",
    srvTeenDesc: "A safe space to vent, figure things out, and handle the pressure.",
    srvPsych: "Psychiatric Therapy",
    srvPsychDesc: "Pro medical advice to help you manage your mental health journey.",
    journeyTitle: "The Glow Up Journey",
    journeySubtitle: "\"Even the darkest nights end, and the sun always pulls up.\"",
    journeyTangled: "The Tangled Mind",
    journeyStep1Title: "Step 1: Reaching Out & Keeping it Real",
    journeyStep1P1: "When anxiety or depression hits hard, your mind feels like a chaotic knot. Even Winston Churchill called his depression his \"black dog.\" He didn't hide it; he owned it.",
    journeyStep1P2: "The first step in therapy is just admitting the knot is there. You don't need to have the answers yet. In our first session, we just vibe, look at the \"black dog\" with no judgment, and slowly start untangling the mess.",
    journeyLight: "Finding the Light",
    journeyStep2Title: "Step 2: Digging Deep & Leveling Up",
    journeyStep2P1: "Abraham Lincoln dealt with crazy \"melancholy\" (depression) but used that exact struggle to build the deep empathy he needed to lead a whole nation.",
    journeyStep2P2: "In therapy, we don't just run from the dark. We figure out your triggers, your past trauma, and toxic patterns. Then, we build legit psychological tools so you can turn your emotional struggles into your biggest flex, just like Lincoln.",
    journeyKintsugi: "The Art of Brokenness",
    journeyStep3Title: "Step 3: Healing, Growth, and Kintsugi",
    journeyStep3P1: "In Japan, when a bowl breaks, they don't trash it. They fix the cracks with gold. That’s called Kintsugi.",
    journeyStep3P2: "The vibe here is deep: your broken moments are part of your story, not something to hide. By the end of therapy, you aren't \"fixed\" to be your old self. You are healed, and your scars—your struggles—are lined with gold. You level up into a stronger, more authentic version of you.",
    journeyCTA: "Main Character Energy Awaits",
    journeyCTADesc: "You don't have to solo this boss battle. Whether your mind feels messy or you're looking for that gold to repair the cracks, we got you.",
    journeyButton: "Slide into WhatsApp to Start",
    "child behavioral problems": "kids behavior issues",
    "Sleep problems": "sleep issues",
    "Stress and Anger Management": "stress & anger management",
    "Fear and Panic Related Issues": "fear & panic issues",
    "Grief and Trauma": "grief & trauma",
    "eating disorders": "food issues",
    "body image issues": "body image",
    "relationship issues": "toxic relationships",
    "depression": "depression",
    "anger management": "anger issues",
    "irrational fear": "overthinking",
    "cognitive distortion": "fake scenarios",
    "gaslighting": "gaslighting",
    "procrastination": "procrastination",
    "intrusive thoughts": "intrusive thoughts",
    "narcissism": "narcissism",
    "social anxiety": "social anxiety",
    "ocd": "ocd",
    "addiction": "addiction",
    "burnout": "burnout",
    "anxiety": "anxiety",
    "stress": "stress",
    "trauma": "trauma",
    footSubtitle: "Clinical Psychologist | Special Educator",
    footDesc: "Helping you navigate through thought, emotion, and identity.",
    footExplore: "Explore",
    footResources: "Resources",
    footBlog: "Blog",
    footPrivacy: "Privacy Policy",
    footConnect: "Connect",
    footEmail: "Email: shubhamsinghal@gmail.com",
    footMobile: "Mobile: +91 8076 449 095",
    footLocation: "Location: SRG hospital, Block E2, Shastri Nagar, New Delhi, Delhi, 110052",
    footRights: "Dr. Shubham Singhal. All rights reserved.",
    trainedTitle: "Trained and Certified From",
    ladderTitle: "Quick Help",
    ladderQ1: "Who are you seeking help for?",
    ladderQ2: "What's the main vibe check needed?",
    ladderQ3: "How long has this been going on?",
    optMyself: "For Me",
    optChild: "My Kid",
    optPartner: "My Partner",
    optOther: "Someone Else",
    optStress: "Stress/Anxiety",
    optSad: "Feeling Low/Depressed",
    optRelation: "Relationship Drama",
    optOverthink: "Overthinking/Panic",
    optDays: "Just started",
    optWeeks: "A few weeks",
    optMonths: "A few months",
    optYears: "A long time (Years)",
    ladderBack: "Back",
    waIntro: "Hi Dr. Shubham, I am reaching out for",
    waBecause: "because the main issue is",
    waAnd: "and this has been going on for",
  }
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState("en");

  const t = (key) => translations[lang]?.[key] || translations["en"][key] || key;

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
